# Generated by Django 5.2 on 2025-04-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, default='blog/images/default_post_image.webp', help_text='Upload a featured image for this post (recommended size: 1200x630px),', null=True, upload_to='blog/images/%Y/%m/%d/'),
        ),
    ]
